version: '3.8'

services:
  routexia-admin-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: routexia-nestjs-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL:-postgres://neondb_owner:npg_sample_pass@ep-routexia-db.ap-southeast-1.aws.neon.tech/routexia?sslmode=require}
      - JWT_SECRET=${JWT_SECRET:-RouteXia_Super_Secret_JWT_Key_2026_Enterprise!}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@routexia.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin123456!}
